server:
  port: 8082
  error.include-message: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    default-models-expand-depth: -1
  api-docs.path: /openapi/v3/api-docs
  pathsToMatch: /**
  packagesToScan: com.i3market

delayTime:
  getElementDelayTime: 1

#Config for API documentation
api:
  common:
    version: 1.0.0
    title: i3Market Semantic Engine
    description: Details of the API for the Semantic Engine of the i3Market.
    termsOfService: i3-Market Service
    license: i3-Market License
    licenseUrl: https://www.i3-market.eu/
    externalDocDesc: https://www.i3-market.eu/
    externalDocUrl: https://www.i3-market.eu/
    contact:
      name: Mirza
      url:
      email: mirza.fardeenbaig@insight-centre.org

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, invalid format of the request. See response message for more information
    notFound.description: Not found, the specified input does not exist
    unprocessableEntity.description: Unprocessable entity. See response message for more information
    # Define response for each API here
    saveProviderBadRequest.description: Failed to save provider information
    updateOfferingBadRequest.description: Failed to update data offering

  i3market-semantic-engine:
    save-data-provider:
      description: Register provider info
      notes: |
        # Register provider info

        # Example:
            {
              "providerId": "uiot-provider",
              "name": "",
              "description": "This is UIoT data Provider",
              "organization": [
                {
                  "organizationId": "NUIGP1",
                  "name": "National University of Ireland Galway",
                  "description": "Education Organisation",
                  "address": "University Road, Galway",
                  "contactPoint": "chihung.le@nuigalway.ie"
                }
              ]
            }

        # Expected responses

            If given information is correct:
              200 - Ok, data provider info has been saved into the database sucessfully.

            If given information is incorrect/dublicated/invalid input
              400 - Bad Request** error will be returned

            System down, database has an issue...
              422 - Unprocessable Entity** error will be returned. It would be an issue with database or system down.

    update-offering:
      description: Update an existing data offering
      notes: |
        # Update an existing data offering

        # Expected responses

            If given information is correct:
              200 - Ok, data offering info has been updated/saved into the database sucessfully.

            If given information is incorrect/dublicated/invalid input
              400 - Bad Request error will be returned

            System down, database has an issue...
              422 - Unprocessable Entity** error will be returned. It would be an issue with database or system down.

    get-total-offering:
      description: Get total offering by category and providerId
      notes: |
        # Get total offering by category and providerId
            This total offering will be retrieved from internal database and distributed databases from other nodes

        # Example
            1. Give a category you want to display
                e.g. category = wellbeing
            2. Give a provider fro that category
               e.g. providerId = provider-webri
            3. sortBy : time/title
            4. orderIn : desc/asc


spring:
  application:
    name: SEMANTIC-ENGINE-SERVICE

spring.data.mongodb:
  port: 27018
  authentication-database: admin
  username: root
  password: fe687564-2c56-4e4b-962f-1c2b3367aa9c-4596034d-a2a9-4399-aaf8-34b0c612e5e4
  host: localhost
  database: semantic-engine-database
  auto-index-creation: true

---
category-list:
  url: http://95.211.3.244:7500/data_categories

---
spring.config.activate.on-profile: test-env
spring.data.mongodb.host: mongodb