server:
  port: 8083
  error.include-message: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    default-models-expand-depth: -1
  api-docs.path: /openapi/v3/api-docs
  pathsToMatch: /**
  packagesToScan: com.i3market

delayTime:
  getElementDelayTime: 1

api:
  common:
    version: 1.0.0
    title: I3 Market Semantic Engine API
    description: This is Semantic Engine of i3 Market Project
    termsOfService: i3-Market Service
    license: i3-Market License
    licenseUrl: https://www.i3-market.eu/
    externalDocDesc: https://www.i3-market.eu/
    externalDocUrl: https://www.i3-market.eu/
    contact:
      name: Chi H Le
      url:
      email: lchhung@gmail.com
---
spring:
  application:
    name: SEMANTIC-ENGINE-SERVICE
---
spring.data.mongodb:
  host: mongodb
  port: 27018
  authentication-database: admin
  username: root
  password: fe687564-2c56-4e4b-962f-1c2b3367aa9c-4596034d-a2a9-4399-aaf8-34b0c612e5e4
  #  host: 95.211.3.251
  #  host: localhost
  #  port: 27018
  database: semantic-engine-database
  auto-index-creation: true
---
category-list:
  url: http://95.211.3.244:7500/data_categories

---
spring.config.activate.on-profile: docker
spring.data.mongodb.host: mongodb